import { createActionContext } from "../../core/audit/action-context";
import type { ActionObserver } from "../../core/audit/action-observer";
import type { DomainAuditObserver } from "../../core/audit/domain-audit-observer";
import type { AuthenticatedActor } from "../../core/auth/auth.types";
import { canAccessTarget } from "../../core/auth/authorization";
import type { DatabaseExecutor,TransactionRunner } from "../../core/db/transaction";
import { ApplicationError } from "../../core/errors/application.error";
import type { AssignmentOrganizationValidationService } from "../organization/organization.validation";
import { canAdministerEmployees } from "../employee/employee.scope";
import { assignmentAuditSnapshot } from "../employee/employee.types";
import { parseBusinessDate,parseEmployeeId,parseMoney } from "../employee/employee.validation";
import type { AssignmentCommand } from "./employment-assignment.dto";
import type { AssignmentRecord,AssignmentRepositoryPort } from "./employment-assignment.repository";
export interface EmploymentAssignmentDependencies {repository:AssignmentRepositoryPort;rootExecutor:DatabaseExecutor;transactionRunner:TransactionRunner;organization:AssignmentOrganizationValidationService;actions:ActionObserver;domain:DomainAuditObserver}
const snap=(r:AssignmentRecord)=>assignmentAuditSnapshot({id:r.id,employee_id:r.employeeId,branch_id:r.branchId,department_id:r.departmentId,position_id:r.positionId,employment_type:r.employmentType,base_salary:r.baseSalary,welfare_amount:r.welfareAmount,effective_from:r.effectiveFrom,effective_to:r.effectiveTo});
const priorDay=(date:string)=>{const d=new Date(date+"T00:00:00Z");d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10)};
const normalize=(c:AssignmentCommand):AssignmentCommand=>{const effectiveFrom=parseBusinessDate(c.effectiveFrom,"effective_from");const effectiveTo=c.effectiveTo===null?null:parseBusinessDate(c.effectiveTo,"effective_to");if(effectiveTo!==null&&effectiveTo<effectiveFrom)throw new ApplicationError("VALIDATION_ERROR");if(!["full_time","part_time","temporary"].includes(c.employmentType))throw new ApplicationError("VALIDATION_ERROR");return{...c,branchId:String(parseEmployeeId(c.branchId,"branch_id")),departmentId:String(parseEmployeeId(c.departmentId,"department_id")),positionId:String(parseEmployeeId(c.positionId,"position_id")),baseSalary:parseMoney(c.baseSalary,"base_salary"),welfareAmount:parseMoney(c.welfareAmount,"welfare_amount"),effectiveFrom,effectiveTo}};
export const createEmploymentAssignmentService=(d:EmploymentAssignmentDependencies)=>({
 async createAssignmentInTransaction(executor:DatabaseExecutor,c:AssignmentCommand&{actor:AuthenticatedActor;employeeId:string}){const employeeId=String(parseEmployeeId(c.employeeId,"employee_id"));if(!(await d.repository.employeeIsActive(executor,employeeId)))throw new ApplicationError("RESOURCE_NOT_FOUND");const input=normalize(c);await d.organization.validateActiveAssignmentPath(executor,input);const latest=await d.repository.findLatest(executor,employeeId);if(latest)throw new ApplicationError("EFFECTIVE_DATE_OVERLAP");return d.repository.insert(executor,employeeId,c.actor.accountId,input)},
 async listAssignments(command:{actor:AuthenticatedActor;requestId:string;employeeId:string}){const id=String(parseEmployeeId(command.employeeId,"employee_id"));const context=createActionContext({actor:command.actor,requestId:command.requestId,actionBase:"employee.assignment.list",target:{tableName:"employment_assignments",recordId:id}});return d.actions.observeRead(context,async()=>{if(!canAdministerEmployees(command.actor))throw new ApplicationError("FORBIDDEN_SCOPE");return d.repository.list(d.rootExecutor,id)})},
 async createAssignment(command:AssignmentCommand&{actor:AuthenticatedActor;requestId:string;employeeId:string}){const employeeId=String(parseEmployeeId(command.employeeId,"employee_id"));const context=createActionContext({actor:command.actor,requestId:command.requestId,actionBase:"employee.assignment.create",target:{tableName:"employment_assignments",recordId:employeeId}});return d.actions.observeMutation(context,()=>d.transactionRunner.transaction(async executor=>{if(!canAdministerEmployees(command.actor))throw new ApplicationError("FORBIDDEN_SCOPE");if(!(await d.repository.employeeIsActive(executor,employeeId)))throw new ApplicationError("RESOURCE_NOT_FOUND");const input=normalize(command);await d.organization.validateActiveAssignmentPath(executor,input);const latest=await d.repository.findLatest(executor,employeeId);let closed:AssignmentRecord|null=null;if(latest){if(input.effectiveFrom<=latest.effectiveFrom||(latest.effectiveTo!==null&&input.effectiveFrom<=latest.effectiveTo))throw new ApplicationError("EFFECTIVE_DATE_OVERLAP");if(latest.effectiveTo===null){closed=await d.repository.close(executor,latest.id,priorDay(input.effectiveFrom));if(!closed)throw new ApplicationError("STATE_CONFLICT")}}const created=await d.repository.insert(executor,employeeId,command.actor.accountId,input);const receipt=await d.domain.record(executor,context,{oldData:closed?snap(latest!):undefined,newData:snap(created)});return d.domain.complete({created,closed},receipt)}))},
 async getEmployeeContextAtDate(command:{actor:AuthenticatedActor;employeeId:string;date:string}){const employeeId=String(parseEmployeeId(command.employeeId,"employee_id"));const date=parseBusinessDate(command.date,"date");const context=createActionContext({actor:command.actor,requestId:"employee-context-"+employeeId+"-"+date,actionBase:"employee.assignment.list",target:{tableName:"employment_assignments",recordId:employeeId}});return d.actions.observeRead(context,async()=>{const assignment=await d.repository.findAtDate(d.rootExecutor,employeeId,date);if(!assignment)return{employeeId,date,assignment:null};const self=canAccessTarget(command.actor,{scope:"self",employeeId});const scoped=canAccessTarget(command.actor,{scope:"department",branchId:assignment.branchId,departmentId:assignment.departmentId});if(!self&&!scoped)throw new ApplicationError("RESOURCE_NOT_FOUND");return{employeeId,date,assignment}})},
});
export type EmploymentAssignmentService=ReturnType<typeof createEmploymentAssignmentService>;
