export const errorCodes = [
  "MALFORMED_REQUEST",
  "AUTH_REQUIRED",
  "INVALID_CREDENTIALS",
  "ACCOUNT_DISABLED",
  "FORBIDDEN_SCOPE",
  "ORIGIN_NOT_ALLOWED",
  "JSON_CONTENT_TYPE_REQUIRED",
  "RESOURCE_NOT_FOUND",
  "DUPLICATE_CODE",
  "DUPLICATE_IDENTITY",
  "DUPLICATE_USERNAME",
  "EMPLOYEE_ACCOUNT_ALREADY_EXISTS",
  "DUPLICATE_ROLE_GRANT",
  "STATE_CONFLICT",
  "VALIDATION_ERROR",
  "INVALID_ROLE_SCOPE",
  "INVALID_ORGANIZATION_RELATION",
  "PAYROLL_CONFIGURATION_OVERLAP",
  "PAYROLL_CONFIGURATION_MISSING",
  "PAYROLL_PERIOD_DUPLICATE",
  "PAYROLL_PERIOD_NOT_FOUND",
  "PAYROLL_PERIOD_LOCKED",
  "PAYROLL_PERIOD_STATE_CONFLICT",
  "PAYROLL_ATTENDANCE_INCOMPLETE",
  "PAYROLL_APPROVALS_PENDING",
  "PAYROLL_ASSIGNMENT_MISSING",
  "PAYROLL_NEGATIVE_NET_PAY",
  "PAYROLL_TOTAL_MISMATCH",
  "PAYROLL_ADJUSTMENT_INVALID",
  "PAYROLL_ADJUSTMENT_STATE_CONFLICT",
  "EFFECTIVE_DATE_OVERLAP",
  "PRIMARY_BANK_ACCOUNT_CONFLICT",
  "ACCOUNT_LOCKED",
  "INTERNAL_ERROR",
] as const;

export type ErrorCode = (typeof errorCodes)[number];

export const errorStatusByCode = {
  MALFORMED_REQUEST: 400,
  AUTH_REQUIRED: 401,
  INVALID_CREDENTIALS: 401,
  ACCOUNT_DISABLED: 403,
  FORBIDDEN_SCOPE: 403,
  ORIGIN_NOT_ALLOWED: 403,
  JSON_CONTENT_TYPE_REQUIRED: 415,
  RESOURCE_NOT_FOUND: 404,
  DUPLICATE_CODE: 409,
  DUPLICATE_IDENTITY: 409,
  DUPLICATE_USERNAME: 409,
  EMPLOYEE_ACCOUNT_ALREADY_EXISTS: 409,
  DUPLICATE_ROLE_GRANT: 409,
  STATE_CONFLICT: 409,
  VALIDATION_ERROR: 422,
  INVALID_ROLE_SCOPE: 422,
  INVALID_ORGANIZATION_RELATION: 422,
  PAYROLL_CONFIGURATION_OVERLAP: 409,
  PAYROLL_CONFIGURATION_MISSING: 422,
  PAYROLL_PERIOD_DUPLICATE: 409,
  PAYROLL_PERIOD_NOT_FOUND: 404,
  PAYROLL_PERIOD_LOCKED: 409,
  PAYROLL_PERIOD_STATE_CONFLICT: 409,
  PAYROLL_ATTENDANCE_INCOMPLETE: 409,
  PAYROLL_APPROVALS_PENDING: 409,
  PAYROLL_ASSIGNMENT_MISSING: 422,
  PAYROLL_NEGATIVE_NET_PAY: 422,
  PAYROLL_TOTAL_MISMATCH: 500,
  PAYROLL_ADJUSTMENT_INVALID: 422,
  PAYROLL_ADJUSTMENT_STATE_CONFLICT: 409,
  EFFECTIVE_DATE_OVERLAP: 409,
  PRIMARY_BANK_ACCOUNT_CONFLICT: 409,
  ACCOUNT_LOCKED: 423,
  INTERNAL_ERROR: 500,
} as const satisfies Record<ErrorCode, number>;

export const errorMessageByCode = {
  MALFORMED_REQUEST: "The request could not be understood.",
  AUTH_REQUIRED: "Authentication is required.",
  INVALID_CREDENTIALS: "The username or password is incorrect.",
  ACCOUNT_DISABLED: "This account is disabled.",
  FORBIDDEN_SCOPE: "You do not have permission to perform this action.",
  ORIGIN_NOT_ALLOWED: "The request origin is not allowed.",
  JSON_CONTENT_TYPE_REQUIRED: "A JSON request body is required.",
  RESOURCE_NOT_FOUND: "The requested resource was not found.",
  DUPLICATE_CODE: "That organization code is already in use.",
  DUPLICATE_IDENTITY: "That employee identity is already in use.",
  DUPLICATE_USERNAME: "That username is already in use.",
  EMPLOYEE_ACCOUNT_ALREADY_EXISTS: "That employee already has an account.",
  DUPLICATE_ROLE_GRANT: "That role grant already exists.",
  STATE_CONFLICT: "The requested change conflicts with the current state.",
  VALIDATION_ERROR: "The submitted data is invalid.",
  INVALID_ROLE_SCOPE: "The role scope is invalid.",
  INVALID_ORGANIZATION_RELATION: "The organization scope is invalid.",
  PAYROLL_CONFIGURATION_OVERLAP: "The payroll configuration effective range overlaps an existing value.",
  PAYROLL_CONFIGURATION_MISSING: "A required payroll configuration is missing.",
  PAYROLL_PERIOD_DUPLICATE: "A payroll period already exists for that shop and month.",
  PAYROLL_PERIOD_NOT_FOUND: "The payroll period was not found.",
  PAYROLL_PERIOD_LOCKED: "The payroll period is locked and cannot be changed.",
  PAYROLL_PERIOD_STATE_CONFLICT: "The payroll period is not in a valid state for this action.",
  PAYROLL_ATTENDANCE_INCOMPLETE: "Attendance is incomplete for the payroll period.",
  PAYROLL_APPROVALS_PENDING: "Approvals affecting the payroll period are still pending.",
  PAYROLL_ASSIGNMENT_MISSING: "An effective employment assignment is missing.",
  PAYROLL_NEGATIVE_NET_PAY: "Payroll cannot be completed because net pay would be negative.",
  PAYROLL_TOTAL_MISMATCH: "Payroll totals could not be reconciled.",
  PAYROLL_ADJUSTMENT_INVALID: "The payroll adjustment is invalid.",
  PAYROLL_ADJUSTMENT_STATE_CONFLICT: "The payroll adjustment is not in a valid state for this action.",
  EFFECTIVE_DATE_OVERLAP: "The effective dates overlap an existing period.",
  PRIMARY_BANK_ACCOUNT_CONFLICT: "The primary bank account conflicts with the current state.",
  ACCOUNT_LOCKED: "This account is temporarily locked.",
  INTERNAL_ERROR: "An unexpected error occurred.",
} as const satisfies Record<ErrorCode, string>;
